openapi: 3.0.3
info:
  title: onecx-ai-ui-bff
  version: '1.0'
paths:
  /aIKnowledgeDocument/search:
    post:
      operationId: searchAIKnowledgeDocuments
      tags:
        - AIKnowledgeDocumentBffService
      description: This operation performs a search based on provided search criteria.
        Search for aIKnowledgeDocument results.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIKnowledgeDocumentSearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIKnowledgeDocumentSearchResponse'
        '400':
          description: Bad request
        '500':
          description: Something went wrong
components:
  schemas:
    AIKnowledgeDocument:
      type: object
      required:
        - id
        - name
      properties:
        modificationCount:
          type: integer
          format: int32
        id:
          type: integer
          format: int32
        name:
          type: string
        # "ACTION S1: add additional properties here"
    AIKnowledgeDocumentSearchRequest:
      type: object
      properties:
        limit:
          type: integer
          maximum: 2500
        id:
          type: integer
          format: int32
        name:
          type: string
        # " ACTION S1: Add additional properties to the <feature>-bff.yaml"
    AIKnowledgeDocumentSearchResponse:
      type: object
      required:
        - results
        - totalNumberOfResults
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/AIKnowledgeDocument'
        totalNumberOfResults:
          type: integer
          format: int32
          description: Total number of results on the server.
