app:
  name: ui
  image:
    repository: onecx/onecx-ai-ui
  routing:
    enabled: true
    path: /mfe/onecxAiUi/
  operator:
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: ./OnecxAiUiModule
          description: OneCX OnecxAiUi Module
          note: OneCX OnecxAiUi UI module auto import via MF operator
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-ai-ui
          tagName: onecx-ai-ui-webcomponent
    permission:
      enabled: true
      spec:
        permissions:
          AI_KNOWLEDGE_VECTOR_DB:
            CREATE: Create aIKnowledgeVectorDb
            EDIT: Edit aIKnowledgeVectorDb
            DELETE: Delete aIKnowledgeVectorDb
            SAVE: Update and save aIKnowledgeVectorDb
            IMPORT: Import aIKnowledgeVectorDb
            EXPORT: Export aIKnowledgeVectorDb
            VIEW: View mode for aIKnowledgeVectorDb
            SEARCH: Search aIKnowledgeVectorDb
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: onecx-ai-ui
